config/routes.rb
Rails.application.routes.draw do
  #get 'site/index'
  root 'site#index'

  devise_for :users
  resources :issues
  resources :sellers
  resources :countries
  resources :publishers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/issue.rb
class Issue < ApplicationRecord

has_one :publisher

def self.search(search)
  where("title LIKE ? OR subtitle LIKE ?", "%#{search}%", "%#{search}%") 
end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  #def index
  #  @issues = Issue.all
  #end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # SEARCH /issues/1
  # SEARCH /issues/1.json
  def index
    @issues = Issue.all
    if params[:search]
      @issues = Issue.search(params[:search]).order("created_at DESC")
    else
      @issues = Issue.all.order("created_at DESC")
      @issues = Issue.all.limit("10")
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :subtitle, :publisher_id, :seller_id, :date_publish, :date_acquisition, :cover_price, :acquisition_price)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :issue_title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, id: :issue_subtitle %>
  </div>

  <div class="field">
    <%= form.label :publisher_id %>
    <%= form.number_field :publisher_id, id: :issue_publisher_id %>
  </div>

  <div class="field">
    <%= form.label :seller_id %>
    <%= form.number_field :seller_id, id: :issue_seller_id %>
  </div>

  <div class="field">
    <%= form.label :date_publish %>
    <%= form.date_field :date_publish, id: :issue_date_publish	 %>
  </div>

  <div class="field">
    <%= form.label :date_acquisition %>
    <%= form.date_field :date_acquisition, id: :issue_date_acquisition %>
  </div>

  <div class="field">
    <%= form.label :cover_price %>
    <%= form.text_field :cover_price, id: :issue_cover_price %>
  </div>

  <div class="field">
    <%= form.label :acquisition_price %>
    <%= form.text_field :acquisition_price, id: :issue_acquisition_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issues</h1>

<%= form_tag(issues_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Issues" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<% if @issues.blank? %>
  <h4>There are no issues containing the term <%= params[:search] %>.</h4>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Publisher</th>
      <th>Seller</th>
      <th>Cover Date</th>
      <th>Acquisition Date</th>
      <th>Cover price</th>
      <th>Acquisition price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.title %></td>
        <td><%= issue.subtitle %></td>
        <td><%= issue.publisher_id %></td>
        <td><%= issue.seller_id %></td>
        <td><%= issue.date_publish %></td>
        <td><%= issue.date_acquisition %></td>
        <td><%= issue.cover_price %></td>
        <td><%= issue.acquisition_price %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>
<br>
<%= link_to 'Back', root_path %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @issue.subtitle %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @issue.publisher_id %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @issue.id_seller_id %>
</p>

<p>
  <strong>Cover date:</strong>
  <%= @issue.date_publish %>
</p>

<p>
  <strong>Acquisition date:</strong>
  <%= @issue.date_acquisition %>
</p>

<p>
  <strong>Cover price:</strong>
  <%= @issue.cover_price %>
</p>

<p>
  <strong>Acquisition price:</strong>
  <%= @issue.acquisition_price %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>